### ISSUE TITLE
Expand the head of the tree with all its modifiers

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#42]
Consider the sentence: William Jefferson "Bill" Clinton is an American politician who served from 1993 to 2001 as the 42nd President of the United States.

The internal representation for this sentence is `[jefferson [politician [american]], [american]]`.

The head of the tree (Jefferson) isn't too important for our use cases, but It would be nice if we could make the head 'William Jefferson "Bill" Clinton'

**Comment by moldot** [comment]
This is more of an aesthetic issue when we want to see the full head of the tree in the demo. A workaround is to tell whoami what the subject is, and whoami will recognize the subject as one unit. It will not solve the 'William Jefferson "Bill" Clinton' case because the subject doesn't match 'Bill Clinton'

**Comment by moldot** [comment]
Closed because whoami now supports custom subject recognition in #56. Push the responsibility back to the client to tell whoami what the subject text and its synonyms are.
