### ISSUE TITLE
Upgrade to latest version of spacy

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#75]
We should upgrade spaCy from `0.99` to `0.100.5` (latest). We should do this before rebuilding WikithingsDB -- the latest version promises a smoother install and model loading process.

Upgrading should also fix #17.

**Comment by alvaromorales** [comment]
I'm re-opening this issue. Whoami depends on spaCy `0.100.5`. It's no longer possible to download the spaCy data needed for this version -- try installing Whoami in a fresh virtualenv, and you'll see that `python -m spacy.en.download all` fails.

Upgrading to the latest version of spaCy (or simply the _next_ version, `0.101.x`) causes **many** tests to fail. Why is that? Did spaCy's internal representation change? Are assumptions made by Whoami no longer valid?

@pondpremt, I'm assigning this to you with the hopes that you can diagnose what's going on.

**Comment by alvaromorales** [comment]
Were you able to look into this?

Being on an old version of spaCy is blocking WikipediaBase development (WikipediaBase depends on whoami). https://github.com/infolab-csail/WikipediaBase/pull/289 can't be merged because Travis fails when trying to download data for spaCy. We need to bump up the spaCy version in whoami, but that's non trivial because of all the test failures.

**Comment by pondpremt** [comment]
The commands for downloading spaCy data changes to `python -m spacy download en`. Does it suffice to just change `.travis.yml` on WikipediaBase for now? 

I will also fix whoami's travis file. Thai said, changing to a new version will cause many whoami unit tests to fail. That's just because the parser model behavior changed in some places, like attaching prepositions in wrong places when it was correct before. So I'm gonna have to modify the tests for all of that also, but the core whoami code shouldn't change

**Comment by alvaromorales** [comment]
Yeah, I'll change `.travis.yml` in WikipediaBase for now. Thanks!

If a later version of spaCy results in worse Whoami performance because of parsing bugs, perhaps you shouldn't upgrade it. My concern was that `v0.100.5` was no longer supported and could not be installed on fresh machines, but that doesn't seem to be the case.

**Comment by michaelsilver** [comment]
It is no longer possible to download the English spaCy models for v0.100.5, so we _do_ need to update.

**Comment by alvaromorales** [comment]
With spaCy `v0.100.5`:

```
$ python -m spacy download en
/usr/bin/python: No module named spacy.__main__; 'spacy' is a package and cannot be directly executed
```

@pondpremt, can you look into this?

**Comment by pondpremt** [comment]
The command `python -m spacy download en` wouldn't syntactically work for older versions of spacy because the old `spacy` module doesn't have an executable in the scope to handle the command. You need to go down to `python -m spacy.en.download all`. (See `spacy/__init__.py` vs `spacy/en/download.py`). However, it seems that spacy has deprecated the old data, so running `python -m spacy.en.download all` would give you a `PackageNotFoundExpcetion`. So as Michael pointed out, we need to upgrade spacy to `1.8`.
