### ISSUE TITLE
Split semicolon-separated sentences

### ISSUE THREAD

**Issue by pondpremt** [infolab-csail/whoami#85]
MainThread - DEBUG - .. whoami exception for: "Slate Run is a tributary to the Scioto River; it flows through the Northwest corner of Upper Arlington, Ohio." ([u'Slate Run', u'Slate Run (Ohio)'])

MainThread - DEBUG - .. whoami exception for: "The X Factor is an Australian television reality music competition, based on the original UK series, to find new singing talent; the winner of which receives a Sony Music Australia recording contract and a new car." ([u'The X Factor (Australia season 4)', u'The X Factor'])

MainThread - DEBUG - .. whoami exception for: "Airedale NHS Foundation Trust is an NHS Foundation Trust based in West and North Yorkshire, England; it also serves part of East Lancashire." ([u'Airedale NHS Foundation Trust', u'Airedale NHS Foundation Trust'])

**Comment by moldot** [comment]
For starters, let just treat semicolon as a sentence separator. Ignore cases where a semicolon may separate complex noun phrases.

**Comment by sfelshin** [comment]
@shu98, when you close an issue due to one or more PRs, you should cross-reference them for future reference.  See https://github.com/blog/1506-closing-issues-via-pull-requests for an easy way to do this in the future, but even though you already merged whichever PR it was, you can still add a comment here cross-referencing the PR, e.g., "Closed by <PR URL>".  I'm reopening this issue as a reminder for you to add the cross-reference, and you can re-close the issue as you add it.

**Comment by sfelshin** [comment]
P.S. But props for remembering to close the issue rather than letting it linger! 👍

**Comment by shu98** [comment]
Closed by #101
